module.exports = {
    bot: function() {
       return {
           "Yêu anh lắm đấy nhé":"vui",
           "Bao nhiêu tình yêu em đều trao cho anh":"vui",
           "Tại sao anh lại ghét ?":"bực",
           "Em hận lời ong bướm, hận kẻ bạc tình":"bực",
           "Tỉnh giấc mộng đi các ông":"buồn",
           "Thương em là điều anh không thể ngờ":"vui",
           "Yêu hay không yêu, không yêu hay yêu nói một lời":"vui",
           "Chàng trai của em, em yêu anh rất nhiều":"vui",
           "Đưa chai trà sữa mà thu tiền tui quánh đó":"bực",
           "Mắt biếc nay còn đâu":"buồn",
           "Hy vọng anh ấy sẽ yêu tôi":"buồn",
           "Gặt hái được nhiều thành công":"vui",
           "Cả một bầu trời đáng iu":"vui",
           "Nhảy chung hông mấy bạn thi tạch":"buồn",
           "Chúc mẹ có ngày Phụ nữ tuyệt vời":"vui",
           "Mong mọi người giúp đỡ":"vui",
           "Mong được như vậy nhỉ...":"buồn",
           "Bớt nói lại cho đỡ khẩu nghiệp nha mấy đứa":"bực",
           "Một số hình ảnh về Báo Tường chào mừng ngày Nhà Giáo Việt Nam 20/11 của tập thể các lớp <3":"vui",
           "Sao anh vô tình em quá anh ơi ....":"buồn",
           "Tôi vẫn đợi tin nhắn cậu này... :( <3":"buồn",
           "Làm gì có ai thương em?? :(":"buồn",
           "Không yêu con A thương con B thích con C bồ con D nhưng trong lòng vẫn còn con A nhưng con A bồ anh E nên đành yêu con D":"buồn",
           "Không hiểu sao thích tấm này ghê??":"vui",
           "Thật đáng sợ":"buồn",
           "Tạm biệt các em":"buồn",
           "Nhớ lắm cái thời vô lo vô nghĩ hồn nhiên vui tươi này...":"buồn",
           "Ước sáng thức dậy thấy mình ở nơi xa, không mệt mỏi suy nghĩ... ":"vui",
           "Câu chuyện kinh dị...tháng 8 phải nhập học":"buồn",
           "Sao nuôi mãi mà không lớn vậy em":"buồn",
           "Mạnh dạn lên sẽ có ny nha cm":"buồn",
           "Quả cover khét lẹt":"Không xác định",
           "Quán nét bây giờ trống lắm ...":"buồn",
           "Nếu như em đợi anh, anh sẽ hoành tráng đến đón em":"buồn",
           "Chơi cái trò mất dại":"bực",
           "Tự hào quá Việt Nam ơi":"vui",
           "Trùm ăn hại":"bực",
           "Ăn rồi cứ la tui quài":"bực",
           "Đẹp quên lối về :(":"buồn",
           "Đi chơi với con gái mà không mang tiền :)":"bình thường",
           "Con mất dại dám cắn tao":"bực",
           "Có chồng rồi giờ khổ thật :( ":"buồn",
           "Thằng chồng suốt ngày nhậu nhẹt :/":"bực",
           "Cảm ơn chị nhoa":"vui",
           "Đã mua máy ở đây r.Chủ Shop cực kì dễ thương máy móc ok khuyến mãi khủng":"vui",
           "Nhạt cũng là 1 ưu điểm à :)":"bình thường",
           "Nè :v không đc hở hang vs ông nào đó nhe :v của tui của tui của tui của tui :v":"vui",
           "t thẳng r nè :)":"bình thường",
           "Môn Toán có điểm trung bình là 5,64 điểm và có 12 bài thi đạt điểm 10":"Không xác định",
           "Thương cho roi cho vọt =)":"vui",
           "Không phải ai cũng có thể uống sữa đâu nha":"Không xác định",
           "Em định dùng nhận dạng giọng nói cho EBot của em của win10 mà không có hỗ trợ tiếng việt, ai làm về nhận dạng giọng nói rồi giúp em với ạ":"Không xác định",
           "<3 Ad nghĩ món này anh em sẽ thích :) <3 Machine learning map. Nhìn vào map and em hiểu được tổng thể về machine learning và dễ chọn nhánh và ngành mình học, đỡ phải đi lạc. <3 Ad chúc anh em tìm được đúng con đường anh em đi.":"vui",
           "Hình ad đang chuẩn bị cho tuần tới về list trong python.":"Không xác định",
           "Không biết các bạn học được nhiều không; chứ level python của ad tăng lên đáng kể :)":"vui",
           "Yêu anh lắm đấy nhé, bao nhiêu tình yêu em đều trao cho anh. Nhưng sao anh lại ghét, em hận những ai bạc tình như vậy":"bực",
           "Yêu anh lắm đấy nhé, bao nhiêu tình yêu em đều trao cho anh. Nhưng sao anh lại ghét, em hận những ai bạc tình như vậy, đã thế em cũng ghét cũng hờn anh luôn":"bực"
       }
    }
}